name: Build and Test

permissions:
  checks: write

on:
  push:
    branches:
      - master
      - 'feature/*'
      - 'dev/*'
  pull_request:
    branches:
      - master
      - 'feature/*'
      - 'dev/*'

env:
  # CI copy of MCreator (inside the runner workspace)
  MCREATOR_CHECKOUT_PATH: ${{ github.workspace }}/mcreator-src
  # fallback Gradle version to use when no wrapper is available (adjust if needed)
  FALLBACK_GRADLE_VERSION: '8.5'

jobs:
  build:
    name: Build and Debug
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout plugin repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Checkout MCreator 2025.2
        uses: actions/checkout@v4
        with:
          repository: MCreator/MCreator
          ref: 2025.2.28610
          path: mcreator-src
          fetch-depth: 1

      - name: Debug:show env & top-level
        run: |
          echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
          echo "MCREATOR_CHECKOUT_PATH: $MCREATOR_CHECKOUT_PATH"
          echo "pwd: $(pwd)"
          uname -a
          ls -la || true

      - name: Show plugin gradle wrapper files (debug)
        run: |
          echo "plugin: gradlew exists? $( [ -f ./gradlew ] && echo yes || echo no )"
          echo "plugin: gradle-wrapper.jar exists? $( [ -f ./gradle/wrapper/gradle-wrapper.jar ] && echo yes || echo no )"
          echo "mcreator-src: gradle-wrapper.jar exists? $( [ -f \"$MCREATOR_CHECKOUT_PATH/gradle/wrapper/gradle-wrapper.jar\" ] && echo yes || echo no )"

      - name: Set up JDK 17 (Temurin)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle (installed fallback)
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: ${{ env.FALLBACK_GRADLE_VERSION }}

      - name: Ensure gradlew is executable (if present)
        run: |
          if [ -f ./gradlew ]; then
            chmod +x ./gradlew || true
            echo "made ./gradlew executable"
          else
            echo "no ./gradlew"
          fi

      - name: Prepare gradle cache cleanup
        run: |
          rm -f ~/.mcreator/gradle/caches/modules-2/modules-2.lock || true
          rm -fr ~/.mcreator/gradle/caches/*/plugin-resolution/ || true
          rm -f ~/.mcreator/gradle/caches/minecraft/deobfedDeps/providedDummy.jar || true
          rm -f ~/.mcreator/gradle/caches/minecraft/deobfedDeps/compileDummy.jar || true
          rm -f ~/.gradle/caches/modules-2/modules-2.lock || true
          rm -f ~/.gradle/caches/modules-2/gc.properties || true

      - name: Build with robust logic (wrapper or fallback) — OVERRIDES mcreator_path
        id: build_step
        env:
          # This env var is just for readability; Gradle receives it via -P below.
          mcreator_path: ${{ env.MCREATOR_CHECKOUT_PATH }}
        run: |
          set -euo pipefail
          echo "Starting build decision logic..."
          PLUGIN_GRADLEW="./gradlew"
          PLUGIN_WRAPPER_JAR="./gradle/wrapper/gradle-wrapper.jar"
          MCREATOR_WRAPPER_JAR="${MCREATOR_CHECKOUT_PATH}/gradle/wrapper/gradle-wrapper.jar"
          # Force the project property override so local gradle.properties won't point to C:/...
          PROP_ARG="-Pmcreator_path=${MCREATOR_CHECKOUT_PATH}"

          # Provide extra diagnostics up-front
          echo "Using PROP_ARG: $PROP_ARG"
          echo "plugin gradlew exists? $( [ -f "$PLUGIN_GRADLEW" ] && echo yes || echo no )"
          echo "plugin wrapper jar exists? $( [ -f "$PLUGIN_WRAPPER_JAR" ] && echo yes || echo no )"
          echo "mcreator-src wrapper jar exists? $( [ -f "$MCREATOR_WRAPPER_JAR" ] && echo yes || echo no )"

          # 1) If plugin has gradlew and its own wrapper JAR -> use it (clean)
          if [ -f "$PLUGIN_GRADLEW" ] && [ -f "$PLUGIN_WRAPPER_JAR" ]; then
            echo "Found plugin gradlew + wrapper jar → running plugin ./gradlew"
            ./gradlew --no-daemon clean build --info --stacktrace --warning-mode all $PROP_ARG
            exit 0
          fi

          # 2) If plugin has gradlew but missing wrapper JAR, and mcreator has wrapper JAR -> copy it into plugin and run plugin gradlew
          if [ -f "$PLUGIN_GRADLEW" ] && [ ! -f "$PLUGIN_WRAPPER_JAR" ] && [ -f "$MCREATOR_WRAPPER_JAR" ]; then
            echo "Plugin has gradlew but missing wrapper JAR; copying MCreator's wrapper JAR into plugin..."
            mkdir -p ./gradle/wrapper
            cp "$MCREATOR_WRAPPER_JAR" ./gradle/wrapper/gradle-wrapper.jar
            chmod +x ./gradlew || true
            echo "Invoking plugin ./gradlew (now that wrapper jar is present)"
            ./gradlew --no-daemon clean build --info --stacktrace --warning-mode all $PROP_ARG
            exit 0
          fi

          # 3) If plugin missing gradlew but mcreator has a wrapper script -> attempt to use mcreator's wrapper script (invoke it from plugin root)
          if [ ! -f "$PLUGIN_GRADLEW" ] && [ -f "${MCREATOR_CHECKOUT_PATH}/gradlew" ]; then
            echo "No plugin gradlew, but mcreator-src has gradlew. Attempting to run mcreator-src/gradlew from plugin root (with mcreator_path override)."
            chmod +x "${MCREATOR_CHECKOUT_PATH}/gradlew" || true
            "${MCREATOR_CHECKOUT_PATH}/gradlew" --no-daemon clean build --info --stacktrace --warning-mode all $PROP_ARG
            exit 0
          fi

          # 4) If no usable wrapper but installed gradle present -> use installed gradle with override
          echo "Falling back to installed gradle with prop override (gradle version shown below):"
          gradle -v || true
          gradle --no-daemon clean build --info --stacktrace --warning-mode all $PROP_ARG
        timeout-minutes: 40

      - name: Final debug — list outputs & gradle selection
        if: always()
        run: |
          echo "=== Build outputs (top) ==="
          du -sh build || true
          ls -la build || true
          echo "=== test results (if any) ==="
          ls -la **/build/test-results || true
          echo "=== Last lines of Gradle stdout/stderr (recent logs) ==="
          # Print recent runner logs if present
          if [ -f build/gradle.log ]; then tail -n 200 build/gradle.log; else echo "(no build/gradle.log)"; fi
