name: Build Plugin

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Step 1: Checkout your plugin source
      - name: Checkout plugin
        uses: actions/checkout@v4

      # Step 2: Checkout MCreator source into the expected path
      - name: Checkout MCreator 2025.2
        uses: actions/checkout@v4
        with:
          repository: MCreator/MCreator
          ref: 2025.2.28610
          path: "C:/Program Files/Pylo/MCreator Source/MCreator"

      # Step 3: Set up JDK (MCreator requires Java 17+; adjust if newer)
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      # Step 4: Cache Gradle
      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Step 5: Build plugin with Gradle
      - name: Build plugin
        run: |
          gradlew build
        env:
          mcreator_path: "C:/Program Files/Pylo/MCreator Source/MCreator"
